version = 0.1
[default.deploy.parameters]
stack_name = "samapp"
resolve_s3 = true
s3_prefix = "samapp"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
